import 'dart:typed_data';

// ============================================================
// STRING CODEC — XOR-based secret deobfuscator
// ============================================================
// Plaintext config endpoints, attribution keys and Firebase
// project numbers must never be visible as raw literals inside
// the release APK. They are stored as XOR-encoded byte arrays
// and decoded at runtime through [revealString].
//
// The cipher pad is derived from a project-specific seed phrase
// via a small LCG. The seed is the ONLY value that needs to be
// changed when forking this binary into a new project — every
// other secret can stay the same, but the resulting bytes will
// differ because they were XORed against a different pad.
//
// NOTE: changing the seed invalidates ALL previously encoded
// byte arrays in the project. Re-run tool/encode_keys.dart to
// regenerate them after touching the seed.
// ============================================================

const _seedBytes = <int>[
  // ASCII codes of "yolk_dash_99"
  0x79, 0x6F, 0x6C, 0x6B, 0x5F, 0x64, 0x61, 0x73, 0x68, 0x5F, 0x39, 0x39,
];

// Pad length is intentionally 20 — uneven against the typical 16/32
// expected by reverse-engineering tools, so periodicity is harder to
// spot in static analysis.
const _padLength = 20;

Uint8List _buildCipherPad() {
  if (_seedBytes.isEmpty) return Uint8List(_padLength);

  // Folding step: mix the seed bytes into a 32-bit accumulator using
  // an XOR-rotate-multiply pattern. The starting value 0x9E3779B9 is
  // the well-known golden-ratio constant; the rotate keeps high bits
  // moving so short seeds still produce well-distributed pads.
  var acc = 0x9E3779B9;
  for (final byte in _seedBytes) {
    acc = ((acc ^ byte) * 37 + 0x6BABA1FF) & 0xFFFFFFFF;
    acc = ((acc << 13) | (acc >>> 19)) & 0xFFFFFFFF;
  }

  final pad = Uint8List(_padLength);
  var rolling = acc | 1;
  for (var i = 0; i < pad.length; i++) {
    rolling = (rolling * 1664525 + 1013904223) & 0x7FFFFFFF;
    pad[i] = (rolling >> 7) & 0xFF;
  }
  return pad;
}

final Uint8List _pad = _buildCipherPad();

/// Decodes an XOR-encoded UTF-16 code-point sequence back into a string.
/// Pass byte arrays generated by `tool/encode_keys.dart`.
String revealString(List<int> bytes) {
  if (bytes.isEmpty) return '';
  final buf = StringBuffer();
  for (var i = 0; i < bytes.length; i++) {
    buf.writeCharCode(bytes[i] ^ _pad[i % _pad.length]);
  }
  return buf.toString();
}

/// Encoder helper used exclusively by tooling — kept here so the cipher
/// pad has a single source of truth. Production code never calls this
/// function (it's stripped by Tree Shaking when unused).
List<int> hideString(String plaintext) {
  final cps = plaintext.codeUnits;
  final out = List<int>.filled(cps.length, 0);
  for (var i = 0; i < cps.length; i++) {
    out[i] = cps[i] ^ _pad[i % _pad.length];
  }
  return out;
}
